

import style from './layout.module.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigate from './components/button/navigate/navigate'
import FixedImage from './components/fixedImage/fixedImage'
import ShareClickBtn from './components/button/shareButtons/shareBrn'
import share from '@/public/icons/share.png'
import search from '@/public/icons/search.png'
import Footer from './components/footer/footer'
import Background from './components/background/background'
import { GlobalContextProvider } from './context/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 
  return (

  
    
    <html lang="en">
      
      <body className={inter.className}>

      <main className={style.layoutMain}>

      <GlobalContextProvider>

       <Background/>
     
       <header className={style.layoutSection}>
        
        <FixedImage/>
         <Navigate/>
         <div className={style.shareBtnDiv}>

         <ShareClickBtn
         img = {share}
         
        
         />
         <ShareClickBtn
         img = {search}
        
        
         />
         </div>
         
         </header>

           {children}
 
       <footer>
          <Footer/>
       </footer>

       </GlobalContextProvider>

       </main>
      </body>
    </html>
 
  )
}
