

import style from './layout.module.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/footerAndHeader/footer/footer'
import { GlobalContextProvider } from './context/context'
import Header from './components/footerAndHeader/header/header'

import GlobalDinamikChaild from './components/globalDinamikChild/globalDinamikChild'
import { LoginModalLogik } from './components/logginRegisterModal/modalLogik/loginModalLogik'
import RecoilWrapper from './components/recoilWrapper/recoilWrapper'
import ReduxWrapper from './components/reduxWrapper/reduxWrapper'
import { WrapperFooter, WrapperHeader } from './components/wrapperHeaderAndFooter/wrapperHedAndFot'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Geo.Developers.ge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 
 
  return (

  
    <html lang="en">
      
      <body className={inter.className}>

      <main className={style.layoutMain}>
    <ReduxWrapper>
      <GlobalContextProvider>
          
           <GlobalDinamikChaild/>
          
             <WrapperHeader>
               <LoginModalLogik />
               <Header />
             </WrapperHeader>

             <RecoilWrapper>

                   {children}

             </RecoilWrapper>
             
           <WrapperFooter>
             <Footer/>
           </WrapperFooter>

      </GlobalContextProvider>
    </ReduxWrapper>
       </main>
      </body>
    </html>
 
  )
}
